pipeline:
  name: bns_spring_boot Deploy
  identifier: bns_spring_boot_deploy
  orgIdentifier: sandbox
  projectIdentifier: soto_sandbox
  stages:
    - stage:
        name: Deploy to Dev
        identifier: deploy_to_dev
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: bns_spring_boot
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: bns_spring_boot_dockerhub
                      sources:
                        - identifier: bns_spring_boot_dockerhub
                          type: DockerRegistry
                          spec:
                            tag: <+input>
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gke_sandbox_dev
          execution:
            steps:
              - step:
                  name: Rolling Deployment
                  identifier: rolling_deployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback
                  identifier: rollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        sendGitStatus:
          enabled: true
          name: dev-deploy
    - stage:
        name: Deploy to Staging
        identifier: deploy_to_staging
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            useFromStage:
              stage: deploy_to_dev
          environment:
            environmentRef: Staging
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gke_sandbox_stage
          execution:
            steps:
              - step:
                  name: Rolling Deployment
                  identifier: rolling_deployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback
                  identifier: rollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        sendGitStatus:
          enabled: true
          name: stage-deploy
    - stage:
        name: Approval
        identifier: approval
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approve Prod Deployment
                  identifier: approve_prod
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: Please review and approve the deployment to Production
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
        sendGitStatus:
          enabled: true
          name: prod-approval
    - stage:
        name: Deploy to Prod
        identifier: deploy_to_prod
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            useFromStage:
              stage: deploy_to_dev
          environment:
            environmentRef: Prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gke_sandbox_prod
          execution:
            steps:
              - step:
                  name: Rolling Deployment
                  identifier: rolling_deployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback
                  identifier: rollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        sendGitStatus:
          enabled: true
          name: prod-deploy
